version: '3.8'

services:
  sinatra-app:
    build: .
    ports:
      - "${APP_PORT}:4567"
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:14.10-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
