default: &default
  adapter: postgresql
  encoding: unicode
  pool: 100
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  timeout: 5000
development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>  